= GamesCornerV2

Seconde version de l'application Games Corner.

Application JAVA développée avec les technologies suivantes : 
  
[cols=2*]
|===
|JSF
|2.3

|Primefaces
|6.2

|Hibernate
|5.3

|Java JDK
|1.8

|Tomcat
|9.0

|Postgresql
|42.2.5

|JUnit
|4.10

|SLF4J
|1.7
|===

Dans cette version de l'application, Spring n'a pas été implémenté pour gérer les opérations transverses (DAO, Transactions, Sécurité, ...). 
Ces fonctionnalités sont prises en charge directement par le développeur (Hibernate pour la DAO par exemple).

L'implémentation de Spring est faite dans la première version du projet : https://github.com/Nanometra/GamesCorner

L'objectif de ce projet est de proposer une application web fonctionnelle déployée en locale proposant toutes les fonctionnalités d'un vrai site de e-commerce en ligne.

Le site proposera entre autre :

- [*] L'inscription d'un client avec validation sur les différents champs disponibles.
- [ ] La connexion dudit client avec enregistrement de ses identifiants en session.
- [ ] le mise en place de cookie pour conserver les informations du client pour la prochaine connexion.
- [ ] La mise en place du magasin avec ajout de nouveaux jeux (société, rôle, vidéos) et autres goodies qui seront séparés en catégories, et toutes les autres parties du CRUD.
- [ ] Implémentation du panier transient du client associé à sa session.
 



